let suggestions = [
    "bike",
    "motorcycle",
    "bmw s1000",
    "KAWASAKI h2",
    "  YAMAHA R1",
    "HONDA CBR",
    "abdelrahman alaa",
    "HONDA HORNET",
    "mag camp",
    "YAMAHA MT - 10",
    "DUCATI DIAVEL",
    "helmet",
    "gloves",
    "jacket",
    "SUZUKI BOULEVARD",
    "KAWASAKI H2 SX",
    "YAMAHA FGR",
    "CAN-AM",
    "Bell ",
    "SCORPION ",
    "DAINESE ",
    "ALPINESTAR ",
    "ARCTIVA ",
    "CLOVER ",
    "camp 25-1",
    
];